version: '3'
services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.2.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  nifi1:
    image: apache/nifi:1.9.2
    hostname: nifi1
    container_name: nifi1
    depends_on:
      - zookeeper
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_CLUSTER_IS_NODE: 'true'
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 9190
      NIFI_ZK_CONNECT_STRING: 'zookeeper:2181'
      NIFI_ELECTION_MAX_WAIT: '1 min'

  nifi2:
    image: apache/nifi:1.9.2
    hostname: nifi2
    container_name: nifi2
    depends_on:
      - zookeeper
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      NIFI_WEB_HTTP_PORT: 8081
      NIFI_CLUSTER_IS_NODE: 'true'
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 9190
      NIFI_ZK_CONNECT_STRING: 'zookeeper:2181'
      NIFI_ELECTION_MAX_WAIT: '1 min'